const peliculas = [
  {
    id: 0,
    titulo: "Terminator",
    anio: "2019",
    director: "James Cameron",
    duracion: "90 minutos",
    sinopsis:
      "En un futuro postapocalíptico, las máquinas han tomado el control del mundo. Un cyborg asesino viaja al pasado para eliminar a un líder de la resistencia antes de que nazca. Sin embargo, una guerrera lo seguirá para intentar impedirlo, cambiando así el destino de la humanidad en una guerra que aún no ha comenzado.",
    generos: ["Acción", "Suspenso", "Terror"],
    cover:
      "https://image.tmdb.org/t/p/w600_and_h900_bestv2/9KI49SBnwAOzGcMw1onIki7vd2.jpg",
    imagen:
      "https://myhotposters.com/cdn/shop/products/HP3151_7045de51-d81f-4636-a03e-fca81fdb7d51.jpg?v=1748536868",
    destacada: true,
    popular: true,
    puntuacion: 4.5,
    imagenPresentacion: "",
  },
  {
    id: 1,
    titulo: "La ciudad de las estrellas (La La Land)",
    anio: "2016",
    director: "Damien Chazelle",
    duracion: "128 minutos",
    sinopsis:
      "Mia, una aspirante a actriz, y Sebastian, un apasionado del jazz, se conocen en Los Ángeles mientras luchan por alcanzar sus sueños. A través de un recorrido lleno de amor, música y sacrificios, deberán decidir si su relación puede sobrevivir a las exigencias de sus carreras artísticas.",
    generos: ["Romance", "Musical"],
    cover:
      "https://image.tmdb.org/t/p/w600_and_h900_bestv2/7pFsAaJmiOppVHcldBzg8JKBHwe.jpg",
    imagen:
      "https://m.media-amazon.com/images/S/pv-target-images/08d4af5a313d87716312d3cbd8ecb786ebe9347b7990abf7afbc7c437740391c.jpg",
    popular: true,
    puntuacion: 4.8,
    imagenPresentacion: "",
  },
  {
    id: 2,
    titulo: "El Conjuro",
    anio: "2013",
    director: "James Wan",
    duracion: "112 minutos",
    sinopsis:
      "Basada en una historia real documentada por los reconocidos demonólogos Ed y Lorraine Warren. La película narra el caso de la familia Perron, quienes se mudan a una granja en Rhode Island y comienzan a experimentar fenómenos paranormales cada vez más intensos y peligrosos.",
    generos: ["Terror"],
    cover:
      "https://image.tmdb.org/t/p/w600_and_h900_bestv2/sKuHxkCogdok6YWzTyXYPoo9qd9n.jpg",
    imagen:
      "https://image.tmdb.org/t/p/original/ecKQlAEG95k62SMGhvX83oEqANK.jpg",
    popular: false,
    puntuacion: 4.2,
    imagenPresentacion: "",
  },
  {
    id: 3,
    titulo: "Orgullo y Prejuicio",
    anio: "2005",
    director: "Joe Wright",
    duracion: "129 minutos",
    sinopsis:
      "Lizzie Bennet es una joven inteligente y decidida que vive con sus cuatro hermanas bajo la presión de su madre por casarlas bien. Cuando conoce al rico y aparentemente arrogante Sr. Darcy, se inicia una tensa relación que poco a poco evoluciona, desafiando las normas sociales de su tiempo.",
    generos: ["Romance", "Drama"],
    cover:
      "https://image.tmdb.org/t/p/w600_and_h900_bestv2/oixzLjpyaLagLa8UREts1NiHr6F.jpg",
    imagen:
      "https://image.tmdb.org/t/p/original/ilgqNJgcfY4mXz8IKPIwCq4ovjU.jpg",
    popular: false,
    puntuacion: 4.0,
    imagenPresentacion: "",
  },
  {
    id: 4,
    titulo: "Interestelar",
    anio: "2014",
    director: "Christopher Nolan",
    duracion: "169 minutos",
    sinopsis:
      "En un futuro donde la Tierra se está volviendo inhabitable, un grupo de astronautas se embarca en una misión a través de un agujero de gusano en busca de un nuevo hogar para la humanidad. Mientras viajan por galaxias desconocidas, enfrentan desafíos que pondrán a prueba sus límites físicos y emocionales.",
    generos: ["Ciencia ficción", "Drama"],
    cover: "https://pics.filmaffinity.com/Interstellar-366875261-large.jpg",
    imagen:
      "https://megustaelcine.com/wp-content/uploads/2025/01/Interestelar-6-1024x665.jpg",
    popular: true,
    puntuacion: 4.7,
    imagenPresentacion: "",
  },
  {
    id: 5,
    titulo: "Her",
    anio: "2013",
    director: "Spike Jonze",
    duracion: "126 minutos",
    sinopsis:
      "Theodore, un hombre solitario, desarrolla una relación emocional con un sistema operativo de inteligencia artificial diseñado para adaptarse y evolucionar. A medida que la conexión entre ambos se profundiza, Theodore se enfrenta a preguntas sobre el amor, la conciencia y lo que significa ser humano.",
    generos: ["Romance", "Ciencia ficción", "Drama"],
    cover: "https://www.aceprensa.com/wp-content/uploads/2014/02/152601-0.jpg",
    imagen: "https://cdn.culturagenial.com/es/imagenes/pelicula-her-og.jpg",
    popular: true,
    puntuacion: 4.3,
    imagenPresentacion: "",
  },
  {
    id: 6,
    titulo: "Gladiador",
    anio: "2000",
    director: "Ridley Scott",
    duracion: "155 minutos",
    sinopsis:
      "Maximus, un general romano traicionado y forzado a la esclavitud, se convierte en gladiador. Movido por la sed de justicia y venganza, lucha en la arena del Coliseo con el objetivo de enfrentarse al emperador que destruyó su vida.",
    generos: ["Acción", "Drama", "Histórica"],
    cover:
      "https://cdn.sincroguia.tv/uploads/programs/g/l/a/gladiator-el-gladiador-poster-152_SPA-87_V.jpg",
    imagen:
      "https://m.media-amazon.com/images/S/pv-target-images/94d902fa61a49de21955dafa704d33fe753376c2d5b1063f7e40aaf32ca32ffc.jpg",
    popular: true,
    puntuacion: 4.6,
    imagenPresentacion: "",
  },
  {
    id: 7,
    titulo: "Cisne Negro",
    anio: "2010",
    director: "Darren Aronofsky",
    duracion: "108 minutos",
    sinopsis:
      "Nina, una bailarina perfeccionista, consigue el papel principal en una ambiciosa producción de El lago de los cisnes. A medida que se adentra en la dualidad del personaje, su mente comienza a desmoronarse, llevándola a una espiral de paranoia, obsesión y autodescubrimiento.",
    generos: ["Drama", "Suspenso", "Psicológica"],
    cover: "https://pics.filmaffinity.com/black_swan-861293346-large.jpg",
    imagen:
      "https://s3.amazonaws.com/dam.smashmexico.com.mx/wp-content/uploads/2024/02/el-cisne-negro-final-explicado-pelicula-darren-aronofsky.jpg",
    popular: false,
    puntuacion: 4.1,
    imagenPresentacion: "",
  },
  {
    id: 8,
    titulo: "Up",
    anio: "2009",
    director: "Pete Docter",
    duracion: "96 minutos",
    sinopsis:
      "Carl, un anciano viudo, decide cumplir el sueño de su difunta esposa viajando a Sudamérica en su casa flotante con globos. Sin embargo, inesperadamente se le une un niño explorador que transforma su solitario viaje en una gran aventura llena de emoción y descubrimiento.",
    generos: ["Animación", "Aventura", "Familiar"],
    cover: "https://pics.filmaffinity.com/Up-672315222-large.jpg",
    imagen:
      "https://s1.elespanol.com/2022/01/03/el-cultural/blogs/entreclasicos/639696298_220840702_1706x960.jpg",
    popular: true,
    puntuacion: 4.4,
    imagenPresentacion: "",
  },
  {
    id: 9,
    titulo: "Inception",
    anio: "2010",
    director: "Christopher Nolan",
    duracion: "148 minutos",
    sinopsis:
      "Dom Cobb es un ladrón especializado en infiltrarse en los sueños para robar secretos. Su nueva misión es diferente: debe implantar una idea en la mente de un objetivo. Para lograrlo, deberá navegar por múltiples niveles del subconsciente en una carrera contrarreloj.",
    generos: ["Ciencia ficción", "Acción", "Thriller"],
    cover:
      "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_FMjpg_UX1000_.jpg",
    imagen:
      "https://st1.uvnimg.com/dims4/default/366949e/2147483647/thumbnail/1024x576%3E/quality/75/?url=https%3A%2F%2Fuvn-brightspot.s3.amazonaws.com%2Fassets%2Fvixes%2Fl%2Fleonardo-dicaprio-inception.jpg",
    popular: true,
    puntuacion: 4.9,
    imagenPresentacion: "",
  },
  {
    id: 10,
    titulo: "Amélie",
    anio: "2001",
    director: "Jean-Pierre Jeunet",
    duracion: "122 minutos",
    sinopsis:
      "Amélie es una joven introvertida que vive en París y encuentra alegría en hacer pequeñas buenas acciones por los demás. En su viaje para mejorar la vida de quienes la rodean, también descubrirá el amor y aprenderá a abrir su propio corazón al mundo.",
    generos: ["Romance", "Comedia", "Drama"],
    cover: "https://es.web.img2.acsta.net/pictures/21/06/18/12/28/5014869.jpg",
    imagen:
      "https://lamenteesmaravillosa.com/wp-content/uploads/2020/03/amelie.jpeg",
    popular: false,
    puntuacion: 4.5,
    imagenPresentacion: "",
  },
  {
    id: 11,
    titulo: "Whiplash",
    anio: "2014",
    director: "Damien Chazelle",
    duracion: "107 minutos",
    sinopsis:
      "Andrew es un joven baterista obsesionado con la perfección. Cuando entra al conservatorio de música más prestigioso del país, se encuentra con un instructor despiadado que lo empuja más allá de sus límites, obligándolo a decidir hasta dónde está dispuesto a llegar por la grandeza.",
    generos: ["Drama", "Música"],
    cover:
      "https://m.media-amazon.com/images/M/MV5BN2NiMjY3OTgtMzVmYi00MjIwLTljOWItY2QzYTdiNTFkMTQyXkEyXkFqcGc@._V1_.jpg",
    imagen:
      "https://asalallena.com.ar/wp-content/uploads/2020/07/whiplash-1024x572.jpg",
    popular: true,
    puntuacion: 4.8,
    imagenPresentacion: "",
  },
  {
    id: 12,
    titulo: "Parásitos",
    anio: "2019",
    director: "Bong Joon-ho",
    duracion: "132 minutos",
    sinopsis:
      "La familia Kim, de escasos recursos, encuentra una oportunidad de infiltrarse progresivamente en la vida de una familia rica haciéndose pasar por profesionales calificados. Lo que comienza como una ingeniosa estafa se transforma rápidamente en una historia oscura de desigualdad y consecuencias imprevisibles.",
    generos: ["Drama", "Thriller", "Comedia negra"],
    cover: "https://es.web.img3.acsta.net/pictures/19/09/17/17/13/3740579.jpg",
    imagen:
      "https://hips.hearstapps.com/hmg-prod/images/parasitos-pelicula-1559747669.jpg",
    popular: true,
    puntuacion: 5.0,
    imagenPresentacion: "",
  },
  {
    id: 13,
    titulo: "El Gran Hotel Budapest",
    anio: "2014",
    director: "Wes Anderson",
    duracion: "99 minutos",
    sinopsis:
      "Gustave H, un legendario conserje de un famoso hotel europeo entre guerras, entabla amistad con un joven botones. Juntos se ven envueltos en una intriga de robo de obras de arte, luchas familiares por una herencia y el impacto de la guerra en un mundo decadente y lleno de estilo.",
    generos: ["Comedia", "Drama", "Crimen"],
    cover:
      "https://m.media-amazon.com/images/M/MV5BMTM2MjY1NjgyOF5BMl5BanBnXkFtZTgwNzkzOTI3MDE@._V1_.jpg",
    imagen:
      "https://hips.hearstapps.com/hmg-prod/images/gran-hotel-budapest-cartel-1513779850.jpg",
    popular: false,
    puntuacion: 4.3,
    imagenPresentacion: "",
  },
  {
    id: 14,
    titulo: "El Padrino",
    anio: "1972",
    director: "Francis Ford Coppola",
    duracion: "175 minutos",
    sinopsis:
      "La saga de la familia Corleone, una de las más poderosas familias mafiosas de Nueva York. Entre intrigas, traiciones y luchas por el poder, Michael Corleone lucha por mantener el legado de su familia mientras enfrenta los dilemas morales y las consecuencias de su ascenso al poder.",
    generos: ["Crimen", "Drama"],
    cover:
      "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00ZjQ5LWFmNTEtODM1ZmRlYjQzZThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    imagen:
      "https://okdiario.com/img/2022/02/25/el-padrino-paramount-pictures-655x368.jpg",
    popular: true,
    puntuacion: 4.9,
    imagenPresentacion: "",
  },
  {
    id: 15,
    titulo: "Forrest Gump",
    anio: "1994",
    director: "Robert Zemeckis",
    duracion: "142 minutos",
    sinopsis:
      "La vida de Forrest Gump, un hombre con un coeficiente intelectual bajo pero con un corazón noble, quien de manera accidental es testigo y protagonista de varios de los eventos más importantes de la historia de Estados Unidos en el siglo XX.",
    generos: ["Drama", "Comedia", "Romance"],
    cover: "",
    imagen:
      "https://e8cuz2bphm9.exactdn.com/blog/wp-content/uploads/2018/04/BlogMG04144.jpg?strip=all&lossy=1&quality=75&ssl=1",
    popular: true,
    puntuacion: 4.7,
    imagenPresentacion: "",
  },
  {
    id: 16,
    titulo: "Matrix",
    anio: "1999",
    director: "Hermanas Wachowski",
    duracion: "136 minutos",
    sinopsis:
      "Un programador de computadoras descubre que la realidad que conoce es una simulación creada por máquinas inteligentes para subyugar a la humanidad. Al unirse a un grupo de rebeldes, deberá luchar para liberar a la humanidad de esta ilusión.",
    generos: ["Ciencia ficción", "Acción"],
    cover: "",
    imagen: "https://i.blogs.es/8b8798/06-06-matrix/1366_2000.jpg",
    popular: true,
    puntuacion: 4.6,
    imagenPresentacion: "",
  },
  {
    id: 17,
    titulo: "El Señor de los Anillos: La Comunidad del Anillo",
    anio: "2001",
    director: "Peter Jackson",
    duracion: "178 minutos",
    sinopsis:
      "Un joven hobbit hereda un anillo mágico y emprende un viaje para destruirlo en el Monte del Destino, el único lugar donde puede ser aniquilado. Para ello, deberá unirse a una compañía de personajes diversos y enfrentar peligros inimaginables.",
    generos: ["Fantasía", "Aventura"],
    cover: "",
    imagen:
      "https://i0.wp.com/elgeneracionalpost.com/wp-content/uploads/2024/11/prime-video.jpg?resize=696%2C392&ssl=1",
    popular: true,
    puntuacion: 4.9,
    imagenPresentacion: "",
  },
  {
    id: 18,
    titulo: "Pulp Fiction",
    anio: "1994",
    director: "Quentin Tarantino",
    duracion: "154 minutos",
    sinopsis:
      "Varias historias entrelazadas de criminales en Los Ángeles, incluyendo a dos sicarios, la esposa de un gánster, un boxeador y una pareja de ladrones de poca monta. La película se caracteriza por su estructura narrativa no lineal y sus diálogos ingeniosos.",
    generos: ["Crimen", "Drama", "Thriller"],
    cover: "",
    imagen:
      "https://img.englishcinemakyiv.com/b2E3AzA-XCnvwoLBLnB_G2J-LPMrua7tZcajtCTlPpI/resize:fill:800:450:1:0/gravity:sm/aHR0cHM6Ly9leHBhdGNpbmVtYXByb2QuYmxvYi5jb3JlLndpbmRvd3MubmV0L2ltYWdlcy84ZjEzODlhNi03MTVlLTQ2NDMtYTExNS03M2VlOTA1NzA5MTAuanBn.jpg",
    popular: true,
    puntuacion: 4.8,
    imagenPresentacion: "",
  },
  {
    id: 19,
    titulo: "El Laberinto del Fauno",
    anio: "2006",
    director: "Guillermo del Toro",
    duracion: "118 minutos",
    sinopsis:
      "En el contexto de la posguerra civil española, una niña se adentra en un mundo de fantasía oscuro y mágico, donde debe completar tres peligrosas tareas para demostrar que es una princesa. La realidad y la fantasía se entrelazan en una historia conmovedora y visualmente impactante.",
    generos: ["Fantasía", "Drama", "Bélica"],
    cover: "",
    imagen:
      "https://m.media-amazon.com/images/S/pv-target-images/3e1ee6398c6d17cdb460e7675adb1df21f53766437de0206ff5219dd70b4b55b.jpg",
    popular: false,
    puntuacion: 4.5,
    imagenPresentacion: "",
  },
  {
    id: 20,
    titulo: "Coco",
    anio: "2017",
    director: "Lee Unkrich, Adrian Molina",
    duracion: "105 minutos",
    sinopsis:
      "Miguel, un aspirante a músico, se embarca en un viaje extraordinario a la Tierra de los Muertos para descubrir la verdadera historia de su familia y el legado musical que siempre ha sido prohibido en su hogar.",
    generos: ["Animación", "Aventura", "Familiar"],
    cover: "",
    imagen:
      "https://cdn11.bigcommerce.com/s-4c994/images/stencil/1280x1280/products/1768/2936/Coco_Poster__39353.1515979877.jpg?c=2",
    popular: true,
    puntuacion: 4.7,
    imagenPresentacion: "",
  },
  {
    id: 21,
    titulo: "Blade Runner 2049",
    anio: "2017",
    director: "Denis Villeneuve",
    duracion: "164 minutos",
    sinopsis:
      "Un joven 'blade runner' descubre un secreto enterrado hace mucho tiempo que podría sumir en el caos lo que queda de la sociedad. Su descubrimiento lo lleva a la búsqueda de Rick Deckard, un antiguo 'blade runner' que ha estado desaparecido durante 30 años.",
    generos: ["Ciencia ficción", "Drama", "Thriller"],
    cover: "",
    imagen:
      "https://img.asmedia.epimg.net/resizer/v2/OIEXSPOY7FIYPAIXBNMI4PRBKI.jpg?auth=7e845406df25559a072a118531e00d15e2b7ebfba3e5bd376b023e57d8b219b4&width=1472&height=828&smart=true",
    popular: true,
    puntuacion: 4.6,
    imagenPresentacion: "",
  },
  {
    id: 22,
    titulo: "Spider-Man: Un nuevo universo",
    anio: "2018",
    director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    duracion: "117 minutos",
    sinopsis:
      "Miles Morales se convierte en el Spider-Man de su realidad y cruza caminos con cinco variantes de Spider-Man de otras dimensiones para detener una amenaza para todas las realidades.",
    generos: ["Animación", "Acción", "Aventura"],
    cover: "",
    imagen: "https://pbs.twimg.com/media/DogwIgaWsAARkxy.jpg:large",
    popular: true,
    puntuacion: 4.8,
    imagenPresentacion: "",
  },
  {
    id: 23,
    titulo: "Gran Torino",
    anio: "2008",
    director: "Clint Eastwood",
    duracion: "116 minutos",
    sinopsis:
      "Walt Kowalski, un veterano de la Guerra de Corea, gruñón y racista, se ve obligado a confrontar sus prejuicios cuando su joven vecino Hmong intenta robar su preciado Gran Torino.",
    generos: ["Drama"],
    cover: "",
    imagen: "https://images6.alphacoders.com/505/505212.jpg",
    popular: false,
    puntuacion: 4.5,
    imagenPresentacion: "",
  },
  {
    id: 24,
    titulo: "Dunkerque",
    anio: "2017",
    director: "Christopher Nolan",
    duracion: "106 minutos",
    sinopsis:
      "Cientos de miles de tropas británicas y aliadas están rodeadas por las fuerzas enemigas en las playas de Dunkerque. Atrapados en la playa con el mar a sus espaldas, se enfrentan a una situación imposible a medida que el enemigo se acerca.",
    generos: ["Bélica", "Drama", "Historia"],
    cover: "",
    imagen:
      "https://images.squarespace-cdn.com/content/v1/50e46031e4b0c2f49772822a/1518718103077-L98RTBPZVDKXQPWJ01XH/dunkirk-pan-poster.jpg",
    popular: true,
    puntuacion: 4.4,
    imagenPresentacion: "",
  },
  {
    id: 25,
    titulo: "1917",
    anio: "2019",
    director: "Sam Mendes",
    duracion: "119 minutos",
    sinopsis:
      "Durante la Primera Guerra Mundial, dos jóvenes soldados británicos reciben la orden de cruzar territorio enemigo para entregar un mensaje que podría salvar a 1.600 hombres.",
    generos: ["Bélica", "Drama", "Historia"],
    cover: "",
    imagen:
      "https://occ-0-8407-92.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABecIgDBXb95BX9chnI-CohNhPz6tXYDjIkinIXNju313uFEcTw5-GN_BJtfut83Lj7HCRYv3iTiVfQ0zPdurk-nhsQOW5MlqdNbT.jpg?r=487",
    popular: true,
    puntuacion: 4.6,
    imagenPresentacion: "",
  },
  {
    id: 26,
    titulo: "Rescatando al Soldado Ryan",
    anio: "1998",
    director: "Steven Spielberg",
    duracion: "169 minutos",
    sinopsis:
      "Un grupo de soldados estadounidenses cruza las líneas enemigas para rescatar a un paracaidista cuyos hermanos han muerto en combate.",
    generos: ["Bélica", "Drama", "Historia"],
    cover: "",
    imagen: "https://i.blogs.es/cc764b/salvar-al-soldado-ryan/1366_2000.jpeg",
    popular: true,
    puntuacion: 4.8,
    imagenPresentacion: "",
  },
  {
    id: 27,
    titulo: "La Caída",
    anio: "2004",
    director: "Oliver Hirschbiegel",
    duracion: "156 minutos",
    sinopsis:
      "Durante los últimos días del Tercer Reich, Adolf Hitler se atrinchera en su búnker mientras Berlín cae bajo el asedio soviético.",
    generos: ["Bélica", "Drama", "Historia"],
    cover: "",
    imagen: "https://e.rpp-noticias.io/xlarge/2019/02/16/392239_753686.jpg",
    popular: false,
    puntuacion: 4.3,
    imagenPresentacion: "",
  },
  {
    id: 28,
    titulo: "Corazones de Hierro",
    anio: "2014",
    director: "David Ayer",
    duracion: "134 minutos",
    sinopsis:
      "Durante los últimos días de la Segunda Guerra Mundial, una tripulación de un tanque estadounidense debe enfrentarse a una misión prácticamente suicida tras las líneas enemigas.",
    generos: ["Bélica", "Drama", "Acción"],
    cover: "",
    imagen:
      "https://storage.googleapis.com/scb22uploads/2015/01/715b9c96-corazones-de-acero-brad-pitt-1030x579.jpeg",
    popular: false,
    puntuacion: 4.2,
    imagenPresentacion: "",
  },
  {
    id: 29,
    titulo: "Hasta el Último Hombre",
    anio: "2016",
    director: "Mel Gibson",
    duracion: "139 minutos",
    sinopsis:
      "La historia real de Desmond Doss, un objetor de conciencia que sirvió como médico de combate durante la batalla de Okinawa sin portar armas y salvó a 75 hombres.",
    generos: ["Bélica", "Drama", "Biografía"],
    cover: "",
    imagen:
      "https://i0.wp.com/noescinetodoloquereluce.com/wp-content/uploads/2016/11/hasta-el-ultimo-hombre.png?fit=900%2C500&ssl=1",
    popular: true,
    puntuacion: 4.7,
    imagenPresentacion: "",
  },
  {
    id: 30,
    titulo: "Intensamente",
    anio: "2015",
    director: "Pete Docter",
    duracion: "95 minutos",
    sinopsis:
      "Riley es una niña que debe adaptarse a una nueva ciudad, mientras sus emociones —Alegría, Tristeza, Ira, Temor y Desagrado— luchan por guiarla a través de la vida.",
    generos: ["Animación", "Aventura", "Comedia"],
    cover: "",
    imagen: "https://pbs.twimg.com/media/CC7Hjt5XIAAuXm5.jpg",
    popular: true,
    puntuacion: 4.6,
    imagenPresentacion: "",
  },
  {
    id: 32,
    titulo: "El viaje de Chihiro",
    anio: "2001",
    director: "Hayao Miyazaki",
    duracion: "125 minutos",
    sinopsis:
      "Chihiro, una niña de 10 años, queda atrapada en un mundo mágico donde los humanos se transforman en animales y los dioses habitan casas de baños. Para salvar a sus padres, deberá encontrar su valentía y su identidad.",
    generos: ["Animación", "Fantasía", "Aventura"],
    cover: "",
    imagen:
      "https://wallpapers.com/images/hd/chihiro-with-flowers-spirited-away-desktop-23jalf8hz2qkoxrh.jpg",
    popular: true,
    puntuacion: 4.9,
    imagenPresentacion: "",
  },
];

export default peliculas;
